DROP TABLE IF EXISTS DOMICILIO;
CREATE TABLE DOMICILIO (
ID INT AUTO_INCREMENT PRIMARY KEY,
CALLE VARCHAR(100) NOT NULL,
NUMERO INT NOT NULL,
LOCALIDAD VARCHAR(100) NOT NULL,
PROVINCIA VARCHAR(100) NOT NULL);

DROP TABLE IF EXISTS PACIENTE;
CREATE TABLE PACIENTE (
ID INT AUTO_INCREMENT PRIMARY KEY,
APELLIDO VARCHAR(100) NOT NULL,
NOMBRE VARCHAR(100) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
DNI INT NOT NULL,
FECHA_INGRESO DATE NOT NULL,
DOMICILIO_ID INT NOT NULL);

INSERT INTO DOMICILIO (CALLE, NUMERO, LOCALIDAD, PROVINCIA) VALUES
 ('Calle A',154,'Salta','Salta');
INSERT INTO PACIENTE (APELLIDO, NOMBRE, EMAIL, DNI, FECHA_INGRESO, DOMICILIO_ID) VALUES
 ('Baspineiro','Rodolfo','qwe@gmail.com',154,'2022-06-09',1);

DROP TABLE IF EXISTS ODONTOLOGO;

CREATE TABLE ODONTOLOGO (
ID INT AUTO_INCREMENT PRIMARY KEY,
APELLIDO VARCHAR(100) NOT NULL,
NOMBRE VARCHAR(100) NOT NULL,
MATRICULA INT NOT NULL);

INSERT INTO ODONTOLOGO (APELLIDO, NOMBRE, MATRICULA) VALUES
('Muelas','Pedro',480);